stages:
- test

test:
  stage: test
  image: ruby:2.5.1-alpine3.7
  variables:
    RAILS_ENV: test
  script:
  - apt-get update -qy
  - apt-get install -y nodejs
  - gem install bundler
  - bundle install --path /cache
  - bundle exec rspec
  - bundle exec rubocop
